// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: agent.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FaultType int32

const (
	FaultType_FAULT_TYPE_UNSPECIFIED     FaultType = 0
	FaultType_FAULT_TYPE_CPU_STRESS      FaultType = 1
	FaultType_FAULT_TYPE_NETWORK_LATENCY FaultType = 2
	FaultType_FAULT_TYPE_MEMORY_PRESSURE FaultType = 3
	FaultType_FAULT_TYPE_DISK_FILL       FaultType = 4
)

// Enum value maps for FaultType.
var (
	FaultType_name = map[int32]string{
		0: "FAULT_TYPE_UNSPECIFIED",
		1: "FAULT_TYPE_CPU_STRESS",
		2: "FAULT_TYPE_NETWORK_LATENCY",
		3: "FAULT_TYPE_MEMORY_PRESSURE",
		4: "FAULT_TYPE_DISK_FILL",
	}
	FaultType_value = map[string]int32{
		"FAULT_TYPE_UNSPECIFIED":     0,
		"FAULT_TYPE_CPU_STRESS":      1,
		"FAULT_TYPE_NETWORK_LATENCY": 2,
		"FAULT_TYPE_MEMORY_PRESSURE": 3,
		"FAULT_TYPE_DISK_FILL":       4,
	}
)

func (x FaultType) Enum() *FaultType {
	p := new(FaultType)
	*p = x
	return p
}

func (x FaultType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FaultType) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[0].Descriptor()
}

func (FaultType) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[0]
}

func (x FaultType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FaultType.Descriptor instead.
func (FaultType) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type InjectFaultRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Type            FaultType              `protobuf:"varint,1,opt,name=type,proto3,enum=cloudsentinel.agent.v1.FaultType" json:"type,omitempty"`
	DurationSeconds int32                  `protobuf:"varint,2,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	Parameters      map[string]string      `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InjectFaultRequest) Reset() {
	*x = InjectFaultRequest{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectFaultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectFaultRequest) ProtoMessage() {}

func (x *InjectFaultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectFaultRequest.ProtoReflect.Descriptor instead.
func (*InjectFaultRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *InjectFaultRequest) GetType() FaultType {
	if x != nil {
		return x.Type
	}
	return FaultType_FAULT_TYPE_UNSPECIFIED
}

func (x *InjectFaultRequest) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *InjectFaultRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type InjectFaultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FaultId       string                 `protobuf:"bytes,1,opt,name=fault_id,json=faultId,proto3" json:"fault_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectFaultResponse) Reset() {
	*x = InjectFaultResponse{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectFaultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectFaultResponse) ProtoMessage() {}

func (x *InjectFaultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectFaultResponse.ProtoReflect.Descriptor instead.
func (*InjectFaultResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *InjectFaultResponse) GetFaultId() string {
	if x != nil {
		return x.FaultId
	}
	return ""
}

func (x *InjectFaultResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *InjectFaultResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RollbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FaultId       string                 `protobuf:"bytes,1,opt,name=fault_id,json=faultId,proto3" json:"fault_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackRequest) Reset() {
	*x = RollbackRequest{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackRequest) ProtoMessage() {}

func (x *RollbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackRequest.ProtoReflect.Descriptor instead.
func (*RollbackRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *RollbackRequest) GetFaultId() string {
	if x != nil {
		return x.FaultId
	}
	return ""
}

type RollbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackResponse) Reset() {
	*x = RollbackResponse{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackResponse) ProtoMessage() {}

func (x *RollbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackResponse.ProtoReflect.Descriptor instead.
func (*RollbackResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *RollbackResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RollbackResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

type ActiveFault struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FaultId          string                 `protobuf:"bytes,1,opt,name=fault_id,json=faultId,proto3" json:"fault_id,omitempty"`
	Type             FaultType              `protobuf:"varint,2,opt,name=type,proto3,enum=cloudsentinel.agent.v1.FaultType" json:"type,omitempty"`
	StartedAtUnix    int64                  `protobuf:"varint,3,opt,name=started_at_unix,json=startedAtUnix,proto3" json:"started_at_unix,omitempty"`
	RemainingSeconds int32                  `protobuf:"varint,4,opt,name=remaining_seconds,json=remainingSeconds,proto3" json:"remaining_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ActiveFault) Reset() {
	*x = ActiveFault{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveFault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveFault) ProtoMessage() {}

func (x *ActiveFault) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveFault.ProtoReflect.Descriptor instead.
func (*ActiveFault) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ActiveFault) GetFaultId() string {
	if x != nil {
		return x.FaultId
	}
	return ""
}

func (x *ActiveFault) GetType() FaultType {
	if x != nil {
		return x.Type
	}
	return FaultType_FAULT_TYPE_UNSPECIFIED
}

func (x *ActiveFault) GetStartedAtUnix() int64 {
	if x != nil {
		return x.StartedAtUnix
	}
	return 0
}

func (x *ActiveFault) GetRemainingSeconds() int32 {
	if x != nil {
		return x.RemainingSeconds
	}
	return 0
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActiveFaults  []*ActiveFault         `protobuf:"bytes,1,rep,name=active_faults,json=activeFaults,proto3" json:"active_faults,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *StatusResponse) GetActiveFaults() []*ActiveFault {
	if x != nil {
		return x.ActiveFaults
	}
	return nil
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x16cloudsentinel.agent.v1\"\x0f\n" +
	"\rHealthRequest\"e\n" +
	"\x0eHealthResponse\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\"\x91\x02\n" +
	"\x12InjectFaultRequest\x125\n" +
	"\x04type\x18\x01 \x01(\x0e2!.cloudsentinel.agent.v1.FaultTypeR\x04type\x12)\n" +
	"\x10duration_seconds\x18\x02 \x01(\x05R\x0fdurationSeconds\x12Z\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2:.cloudsentinel.agent.v1.InjectFaultRequest.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"f\n" +
	"\x13InjectFaultResponse\x12\x19\n" +
	"\bfault_id\x18\x01 \x01(\tR\afaultId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\",\n" +
	"\x0fRollbackRequest\x12\x19\n" +
	"\bfault_id\x18\x01 \x01(\tR\afaultId\"F\n" +
	"\x10RollbackResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x0f\n" +
	"\rStatusRequest\"\xb4\x01\n" +
	"\vActiveFault\x12\x19\n" +
	"\bfault_id\x18\x01 \x01(\tR\afaultId\x125\n" +
	"\x04type\x18\x02 \x01(\x0e2!.cloudsentinel.agent.v1.FaultTypeR\x04type\x12&\n" +
	"\x0fstarted_at_unix\x18\x03 \x01(\x03R\rstartedAtUnix\x12+\n" +
	"\x11remaining_seconds\x18\x04 \x01(\x05R\x10remainingSeconds\"Z\n" +
	"\x0eStatusResponse\x12H\n" +
	"\ractive_faults\x18\x01 \x03(\v2#.cloudsentinel.agent.v1.ActiveFaultR\factiveFaults*\x9c\x01\n" +
	"\tFaultType\x12\x1a\n" +
	"\x16FAULT_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15FAULT_TYPE_CPU_STRESS\x10\x01\x12\x1e\n" +
	"\x1aFAULT_TYPE_NETWORK_LATENCY\x10\x02\x12\x1e\n" +
	"\x1aFAULT_TYPE_MEMORY_PRESSURE\x10\x03\x12\x18\n" +
	"\x14FAULT_TYPE_DISK_FILL\x10\x042\x8a\x03\n" +
	"\fAgentService\x12W\n" +
	"\x06Health\x12%.cloudsentinel.agent.v1.HealthRequest\x1a&.cloudsentinel.agent.v1.HealthResponse\x12f\n" +
	"\vInjectFault\x12*.cloudsentinel.agent.v1.InjectFaultRequest\x1a+.cloudsentinel.agent.v1.InjectFaultResponse\x12]\n" +
	"\bRollback\x12'.cloudsentinel.agent.v1.RollbackRequest\x1a(.cloudsentinel.agent.v1.RollbackResponse\x12Z\n" +
	"\tGetStatus\x12%.cloudsentinel.agent.v1.StatusRequest\x1a&.cloudsentinel.agent.v1.StatusResponseBDZBgithub.com/mamoudou-cheikh-kane/cloudsentinel/agent/internal/pb;pbb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_agent_proto_goTypes = []any{
	(FaultType)(0),              // 0: cloudsentinel.agent.v1.FaultType
	(*HealthRequest)(nil),       // 1: cloudsentinel.agent.v1.HealthRequest
	(*HealthResponse)(nil),      // 2: cloudsentinel.agent.v1.HealthResponse
	(*InjectFaultRequest)(nil),  // 3: cloudsentinel.agent.v1.InjectFaultRequest
	(*InjectFaultResponse)(nil), // 4: cloudsentinel.agent.v1.InjectFaultResponse
	(*RollbackRequest)(nil),     // 5: cloudsentinel.agent.v1.RollbackRequest
	(*RollbackResponse)(nil),    // 6: cloudsentinel.agent.v1.RollbackResponse
	(*StatusRequest)(nil),       // 7: cloudsentinel.agent.v1.StatusRequest
	(*ActiveFault)(nil),         // 8: cloudsentinel.agent.v1.ActiveFault
	(*StatusResponse)(nil),      // 9: cloudsentinel.agent.v1.StatusResponse
	nil,                         // 10: cloudsentinel.agent.v1.InjectFaultRequest.ParametersEntry
}
var file_agent_proto_depIdxs = []int32{
	0,  // 0: cloudsentinel.agent.v1.InjectFaultRequest.type:type_name -> cloudsentinel.agent.v1.FaultType
	10, // 1: cloudsentinel.agent.v1.InjectFaultRequest.parameters:type_name -> cloudsentinel.agent.v1.InjectFaultRequest.ParametersEntry
	0,  // 2: cloudsentinel.agent.v1.ActiveFault.type:type_name -> cloudsentinel.agent.v1.FaultType
	8,  // 3: cloudsentinel.agent.v1.StatusResponse.active_faults:type_name -> cloudsentinel.agent.v1.ActiveFault
	1,  // 4: cloudsentinel.agent.v1.AgentService.Health:input_type -> cloudsentinel.agent.v1.HealthRequest
	3,  // 5: cloudsentinel.agent.v1.AgentService.InjectFault:input_type -> cloudsentinel.agent.v1.InjectFaultRequest
	5,  // 6: cloudsentinel.agent.v1.AgentService.Rollback:input_type -> cloudsentinel.agent.v1.RollbackRequest
	7,  // 7: cloudsentinel.agent.v1.AgentService.GetStatus:input_type -> cloudsentinel.agent.v1.StatusRequest
	2,  // 8: cloudsentinel.agent.v1.AgentService.Health:output_type -> cloudsentinel.agent.v1.HealthResponse
	4,  // 9: cloudsentinel.agent.v1.AgentService.InjectFault:output_type -> cloudsentinel.agent.v1.InjectFaultResponse
	6,  // 10: cloudsentinel.agent.v1.AgentService.Rollback:output_type -> cloudsentinel.agent.v1.RollbackResponse
	9,  // 11: cloudsentinel.agent.v1.AgentService.GetStatus:output_type -> cloudsentinel.agent.v1.StatusResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		EnumInfos:         file_agent_proto_enumTypes,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
