# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from . import agent_pb2 as agent__pb2

GRPC_GENERATED_VERSION = "1.80.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in agent_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class AgentServiceStub:
    """AgentService defines operations an orchestrator can invoke on an agent
    to inject controlled faults into the local system.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
            "/cloudsentinel.agent.v1.AgentService/Health",
            request_serializer=agent__pb2.HealthRequest.SerializeToString,
            response_deserializer=agent__pb2.HealthResponse.FromString,
            _registered_method=True,
        )
        self.InjectFault = channel.unary_unary(
            "/cloudsentinel.agent.v1.AgentService/InjectFault",
            request_serializer=agent__pb2.InjectFaultRequest.SerializeToString,
            response_deserializer=agent__pb2.InjectFaultResponse.FromString,
            _registered_method=True,
        )
        self.Rollback = channel.unary_unary(
            "/cloudsentinel.agent.v1.AgentService/Rollback",
            request_serializer=agent__pb2.RollbackRequest.SerializeToString,
            response_deserializer=agent__pb2.RollbackResponse.FromString,
            _registered_method=True,
        )
        self.GetStatus = channel.unary_unary(
            "/cloudsentinel.agent.v1.AgentService/GetStatus",
            request_serializer=agent__pb2.StatusRequest.SerializeToString,
            response_deserializer=agent__pb2.StatusResponse.FromString,
            _registered_method=True,
        )


class AgentServiceServicer:
    """AgentService defines operations an orchestrator can invoke on an agent
    to inject controlled faults into the local system.
    """

    def Health(self, request, context):
        """Health returns the current health of the agent."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def InjectFault(self, request, context):
        """InjectFault starts a fault injection on the local node."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Rollback(self, request, context):
        """Rollback removes any active fault injection."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetStatus(self, request, context):
        """GetStatus returns the current state of active fault injections."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Health": grpc.unary_unary_rpc_method_handler(
            servicer.Health,
            request_deserializer=agent__pb2.HealthRequest.FromString,
            response_serializer=agent__pb2.HealthResponse.SerializeToString,
        ),
        "InjectFault": grpc.unary_unary_rpc_method_handler(
            servicer.InjectFault,
            request_deserializer=agent__pb2.InjectFaultRequest.FromString,
            response_serializer=agent__pb2.InjectFaultResponse.SerializeToString,
        ),
        "Rollback": grpc.unary_unary_rpc_method_handler(
            servicer.Rollback,
            request_deserializer=agent__pb2.RollbackRequest.FromString,
            response_serializer=agent__pb2.RollbackResponse.SerializeToString,
        ),
        "GetStatus": grpc.unary_unary_rpc_method_handler(
            servicer.GetStatus,
            request_deserializer=agent__pb2.StatusRequest.FromString,
            response_serializer=agent__pb2.StatusResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "cloudsentinel.agent.v1.AgentService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "cloudsentinel.agent.v1.AgentService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class AgentService:
    """AgentService defines operations an orchestrator can invoke on an agent
    to inject controlled faults into the local system.
    """

    @staticmethod
    def Health(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/cloudsentinel.agent.v1.AgentService/Health",
            agent__pb2.HealthRequest.SerializeToString,
            agent__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def InjectFault(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/cloudsentinel.agent.v1.AgentService/InjectFault",
            agent__pb2.InjectFaultRequest.SerializeToString,
            agent__pb2.InjectFaultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Rollback(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/cloudsentinel.agent.v1.AgentService/Rollback",
            agent__pb2.RollbackRequest.SerializeToString,
            agent__pb2.RollbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/cloudsentinel.agent.v1.AgentService/GetStatus",
            agent__pb2.StatusRequest.SerializeToString,
            agent__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
